image:
  repository: dockerhub.rnd.amadeus.net/obeimages-docker-release/obe-tools/rhel-obe
  tag: latest
#image:
#  repository: docker.io/wilsonggr/my-spring-boot-app
#  tag: v3

service:
  type: ClusterIP
  port: 8080