apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: abr-test-argocd
   namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wigali/ABR.ARGOCD.git
    targetRevision: HEAD
    path: argocd-deployments/templates
  destination: 
    server: https://kubernetes.default.svc
    namespace: myargoapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true