apiVersion: apps/v1
kind: Deployment
metadata:
  name: abr-first-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abr-first-image
  template:
    metadata:
      labels:
        app:abr-first-image
    spec:
      containers:
        - name: my-spring-boot-app
          image: wilsonggr/my-spring-boot-app:latest
          ports:
            - containerPort: 8080