apiVersion: apps/v1
kind: Deployment
metadata:
  name: abr-first-image
spec:
  selector:
    matchLabels:
      app: abr-first-image
  replicas: 2
  template:
    metadata:
      labels:
        app: abr-first-image
    spec:
      containers:
      - name: test-argocd-service
        image: wilsonggr/my-spring-boot-app
        ports:
        - containerPort: 3000